// <auto-generated />
namespace NyvaProdBC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class troubles_20220810_2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(troubles_20220810_2));
        
        string IMigrationMetadata.Id
        {
            get { return "202208101131283_troubles_2022-08-10_2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
